[package]
name = "valou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue="1.2.1"
strum_macros = "0.23.1"
strum = "0.23.0"
